version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .DockerFile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      DATABASE_HOST: db

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
